name: pre-commit autoupdate
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: |
          pip install --upgrade pip
          pip install pre-commit
          pre-commit autoupdate
          pre-commit run -a
      - uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.AUTOUPDATE_PAT }}
          branch: autoupdate/pre-commit
          title: pre-commit autoupdate
          commit-message: pre-commit autoupdate
          delete-branch: true
